import tailwindcssAnimate from "tailwindcss-animate";
import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
// Design tokens are lifted verbatim from the Stitch "Enterprise SaaS Clarity" system
// (stitch_campus_recruitment_portal_saas/enterprise_saas_clarity/DESIGN.md and the per-page
// tailwind.config blocks). These are the single source of truth — do not adjust values.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#eeefff",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed-dim": "#b4c5ff",
        "primary-fixed": "#dbe1ff",
        "on-surface-variant": "#434655",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        surface: "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary-fixed": "#00174b",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#bcc7de",
        "secondary-fixed": "#d8e3fb",
        "on-tertiary-fixed-variant": "#2f2ebe",
        secondary: "#545f73",
        "secondary-container": "#d5e0f8",
        "on-secondary-container": "#586377",
        "on-secondary-fixed": "#111c2d",
        "on-secondary-fixed-variant": "#3c475a",
        "on-secondary": "#ffffff",
        tertiary: "#3e3fcc",
        "tertiary-container": "#585be6",
        "tertiary-fixed-dim": "#c0c1ff",
        "tertiary-fixed": "#e1e0ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#07006c",
        "on-tertiary-container": "#f1eeff",
        "inverse-primary": "#b4c5ff",
        "inverse-on-surface": "#eff1f3",
        "inverse-surface": "#2d3133",
        outline: "#737686",
        "outline-variant": "#c3c6d7",
        "surface-tint": "#0053db",
        primary: "#004ac6",
        "primary-container": "#2563eb",
        background: "#f7f9fb",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "section-padding": "120px",
        gutter: "24px",
        "container-max": "1440px",
        "margin-mobile": "20px",
        "margin-desktop": "80px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
      },
      fontSize: {
        "display-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
      },
      boxShadow: {
        ambient: "0 10px 15px -3px rgba(0,0,0,0.05), 0 4px 6px -4px rgba(0,0,0,0.05)",
        card: "0 1px 3px 0 rgba(0,0,0,0.06), 0 1px 2px -1px rgba(0,0,0,0.06)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [tailwindcssAnimate, forms],
};
